project:
  type: book

book:
  title: "Google Earth Engine for OSINT"
  author: "[Dr. Ollie Ballinger](https://oballinger.github.io)"
  date: "10/6/2022"
  chapters:
    - index.qmd
    - part: "Learning"
      chapters:
        - ch1.qmd
        - ch2.qmd
        - ch3.qmd
        - ch4.qmd
    - part: "Case Studies"
      chapters:
        - SyriaNTL.qmd
        - RojavaRefineries.qmd
  repo-url: https://github.com/oballinger/GEE_OSINT/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  sidebar:
    logo: logo_white.png





bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true

  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
