project:
  type: book
  output-dir: docs

book:
  title: "Google Earth Engine for OSINT"
  author: "[Dr. Ollie Ballinger](https://oballinger.github.io)"
  date: "10/6/2022"
  chapters:
    - index.qmd
    - part: "Learning"
      chapters:
        - ch1.qmd
        - ch2.qmd
        - F1.qmd
        - F2.qmd
        - F4.qmd
        - F5.qmd
        - F6.qmd
    - part: "Case Studies"
      chapters:
        - lights.qmd
        - refineries.qmd
        - ships.qmd
  repo-url: https://github.com/oballinger/GEE_OSINT/
  google-analytics: G-RK9ZLZQ6GL
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: logo_white.png


bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true

  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
